# Generated by Django 5.1.7 on 2025-04-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
